apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APPLICATION_NAME: "api-gateway"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka"
  SPRING_PROFILES_ACTIVE: "default"
