apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  EUREKA_INSTANCE_HOSTNAME: "{{ .Values.config.eurekaHostname }}"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "{{ .Values.config.eurekaDefaultZone }}"
